# Generated by Django 4.1.5 on 2023-02-02 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='email',
            name='identifier',
            field=models.CharField(default='', max_length=30),
        ),
    ]
