# Generated by Django 4.1.5 on 2023-01-30 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facilities', '0002_county_rename_disease_condition_facility_authorized_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='facility',
            name='cover_image',
            field=models.FileField(blank=True, null=True, upload_to='facilities/files/covers/'),
        ),
        migrations.AddField(
            model_name='facility',
            name='icon',
            field=models.FileField(blank=True, null=True, upload_to='facilities/files/icons/'),
        ),
        migrations.AlterField(
            model_name='medicalfile',
            name='file',
            field=models.FileField(upload_to='facilities/files/medical/'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='facilities',
            field=models.ManyToManyField(blank=True, related_name='facilities', to='facilities.facility'),
        ),
    ]
