# Generated by Django 4.1.5 on 2023-01-30 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facilities', '0003_facility_cover_image_facility_icon_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='facility',
            name='icon',
        ),
        migrations.AddField(
            model_name='facility',
            name='address',
            field=models.CharField(default='', max_length=300),
        ),
        migrations.AddField(
            model_name='facility',
            name='latitude',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='facility',
            name='logo',
            field=models.FileField(blank=True, null=True, upload_to='facilities/files/logo/'),
        ),
        migrations.AddField(
            model_name='facility',
            name='longitude',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='facility',
            name='city',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='facility',
            name='contact_no',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='facility',
            name='email',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='facility',
            name='location',
            field=models.CharField(default='', max_length=100),
        ),
    ]
