# Generated by Django 4.1.5 on 2023-01-30 03:04

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('facilities', '0004_remove_facility_icon_facility_address_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Reception',
            new_name='Receptionist',
        ),
    ]
