# Generated by Django 4.1.5 on 2023-01-30 03:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('facilities', '0005_rename_reception_receptionist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='facility',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='patients', to='facilities.facility'),
        ),
    ]
