# Generated by Django 4.1.5 on 2023-01-30 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facilities', '0006_alter_patient_facility'),
    ]

    operations = [
        migrations.AddField(
            model_name='facility',
            name='slug',
            field=models.SlugField(blank=True, max_length=100, null=True),
        ),
    ]
