# Generated by Django 4.1.5 on 2023-01-31 03:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('facilities', '0009_staff_delete_receptionist'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointment',
            old_name='available_slot',
            new_name='date',
        ),
        migrations.RenameField(
            model_name='appointment',
            old_name='description',
            new_name='note',
        ),
        migrations.AddField(
            model_name='appointment',
            name='end_time',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AddField(
            model_name='appointment',
            name='injury',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='facilities.condition'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='start_time',
            field=models.CharField(default='', max_length=10),
        ),
    ]
