# Generated by Django 4.1.5 on 2023-01-31 03:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('facilities', '0010_rename_available_slot_appointment_date_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointment',
            old_name='injury',
            new_name='condition',
        ),
    ]
