# Generated by Django 4.1.5 on 2023-02-17 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facilities', '0013_facility_about_page_content_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='condition',
            name='description',
        ),
        migrations.AddField(
            model_name='condition',
            name='clinical_features',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='condition',
            name='diagnosis',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='condition',
            name='factsheet',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='condition',
            name='pathogen',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='condition',
            name='prevention',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='condition',
            name='transmission',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='condition',
            name='treatment',
            field=models.TextField(blank=True, null=True),
        ),
    ]
