# Generated by Django 4.1.5 on 2023-02-17 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facilities', '0015_facilitytype_facility_owner_name_constituency_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facility',
            name='address',
            field=models.CharField(blank=True, default='', max_length=300),
        ),
        migrations.AlterField(
            model_name='facility',
            name='city',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='facility',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='facility',
            name='location',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
