# Generated by Django 4.1.5 on 2023-02-17 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facilities', '0016_alter_facility_address_alter_facility_city_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facility',
            name='contact_no',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='facility',
            name='email',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
