# Generated by Django 4.1.5 on 2023-02-19 19:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('facilities', '0018_rename_created_appointment_created_on_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='facilitytype',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='service',
            name='doctor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='facilities.doctor'),
        ),
    ]
