# Generated by Django 4.1.5 on 2023-02-20 00:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('facilities', '0019_facilitytype_slug_alter_service_doctor'),
    ]

    operations = [
        migrations.AddField(
            model_name='facility',
            name='facility_kind',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='medicalfile',
            name='appointment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appointment_medical_files', to='facilities.appointment'),
        ),
        migrations.AlterField(
            model_name='medicalfile',
            name='encounter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='encounter_medical_files', to='facilities.encounter'),
        ),
        migrations.AlterField(
            model_name='qualification',
            name='doctor',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='qualifications', to='facilities.doctor'),
        ),
    ]
