# Generated by Django 4.1.5 on 2023-02-21 12:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('facilities', '0021_alter_constituency_county'),
    ]

    operations = [
        migrations.AlterField(
            model_name='constituency',
            name='county',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='facilities.county'),
        ),
    ]
