# Generated by Django 4.1.5 on 2023-02-21 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facilities', '0022_alter_constituency_county'),
    ]

    operations = [
        migrations.AddField(
            model_name='facility',
            name='shared_encounters',
            field=models.ManyToManyField(blank=True, null=True, related_name='shared_encounters', to='facilities.encounter'),
        ),
        migrations.AlterField(
            model_name='facility',
            name='facility_kind',
            field=models.CharField(blank=True, choices=[('pharmacy', 'Pharmacy'), ('clinic', 'Clinic'), ('nutraceuticals', 'Nutraceuticals')], max_length=100, null=True),
        ),
    ]
