# Generated by Django 4.1.5 on 2023-02-21 18:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('facilities', '0023_facility_shared_encounters_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='doctor',
            old_name='status',
            new_name='available',
        ),
    ]
