# Generated by Django 4.1.5 on 2023-02-21 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facilities', '0024_rename_status_doctor_available'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facility',
            name='shared_encounters',
            field=models.ManyToManyField(blank=True, related_name='shared_encounters', to='facilities.encounter'),
        ),
    ]
