# Generated by Django 4.1.5 on 2023-02-21 18:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('facilities', '0025_alter_facility_shared_encounters'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patient',
            old_name='make_account_sharable',
            new_name='account_sharable',
        ),
    ]
