# Generated by Django 4.1.5 on 2023-02-02 02:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('mailer', '0002_email_identifier'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app', models.CharField(blank=True, default='main', max_length=30, null=True, unique=True)),
                ('application_url', models.CharField(blank=True, max_length=255, null=True)),
                ('listing_activated', models.BooleanField(default=True)),
                ('account_creation_activated', models.BooleanField(default=True)),
                ('activate_account_email', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='account_activation_email', to='mailer.email')),
                ('activate_account_emailconfig', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='account_activation_email_config', to='mailer.emailconfiguration')),
                ('order_placement_email', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_placement_email', to='mailer.email')),
                ('order_placement_emailconfig', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_placement_emailconfig', to='mailer.emailconfiguration')),
                ('payment_made_email', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment_made_email', to='mailer.email')),
                ('payment_made_emailconfig', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment_made_emailconfig', to='mailer.emailconfiguration')),
                ('reset_password_email', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='password_reset_Email', to='mailer.email')),
                ('reset_password_emailconfig', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='password_reset_email_config', to='mailer.emailconfiguration')),
            ],
        ),
    ]
