# Generated by Django 4.1.5 on 2023-02-22 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0006_blog_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_on', models.DateTimeField(auto_created=True, auto_now=True)),
                ('created_on', models.DateTimeField(auto_created=True, auto_now_add=True)),
                ('author', models.CharField(max_length=100)),
                ('comment', models.TextField()),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
    ]
