# Generated by Django 4.1.5 on 2023-02-22 18:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0007_reply'),
    ]

    operations = [
        migrations.AddField(
            model_name='reply',
            name='blog',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mainapp.blog'),
        ),
    ]
