# Generated by Django 4.0.4 on 2023-02-10 07:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pharmacetical', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pharmacy',
            name='applicant_name',
        ),
        migrations.AddField(
            model_name='pharmacy',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pharmcacy_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
