# Generated by Django 4.1.5 on 2023-02-19 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacetical', '0005_remove_pharmacy_user_pharmacy_applicant_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('pharmacy', models.CharField(max_length=255)),
                ('serial', models.CharField(max_length=255)),
                ('brand', models.CharField(max_length=255)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('doe', models.DateField()),
                ('dom', models.DateField()),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='media/pharmacy')),
            ],
        ),
    ]
