# Generated by Django 4.1.5 on 2023-02-19 12:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacetical', '0006_product'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Product',
            new_name='Product_Pharmacy',
        ),
    ]
