# Generated by Django 4.1.5 on 2023-02-19 12:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacetical', '0007_rename_product_product_pharmacy'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Product_Pharmacy',
            new_name='Product',
        ),
    ]
