# Generated by Django 4.1.5 on 2023-02-19 12:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacetical', '0008_rename_product_pharmacy_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='pharmacy',
        ),
    ]
