# Generated by Django 4.1.5 on 2023-02-19 20:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacetical', '0012_pharmacy_latitude_pharmacy_longitude'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pharmacy',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='pharmacy',
            name='longitude',
        ),
    ]
