# Generated by Django 4.1.5 on 2023-02-19 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacetical', '0013_remove_pharmacy_latitude_remove_pharmacy_longitude'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='doe',
        ),
        migrations.RemoveField(
            model_name='product',
            name='serial',
        ),
        migrations.AddField(
            model_name='product',
            name='discount',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='dom',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
