# Generated by Django 4.1.5 on 2023-02-21 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacetical', '0014_remove_product_doe_remove_product_serial_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pharmacy',
            name='attach',
            field=models.ImageField(blank=True, null=True, upload_to='media/pharmacy'),
        ),
        migrations.AddField(
            model_name='product',
            name='code',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pharmacy',
            name='date_created',
            field=models.TextField(blank=True),
        ),
    ]
