# Generated by Django 4.1.5 on 2023-02-24 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacetical', '0016_product_approved_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='live_product',
            field=models.BooleanField(default=False),
        ),
    ]
