# Generated by Django 4.1.5 on 2023-02-24 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacetical', '0017_product_live_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='unapproved',
            field=models.BooleanField(default=False),
        ),
    ]
