# Generated by Django 4.1.5 on 2023-02-24 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacetical', '0018_product_unapproved'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='delivered_order',
            field=models.BooleanField(default=False),
        ),
    ]
