# Generated by Django 4.1.5 on 2023-02-26 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PrescriptionPatient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p_name', models.CharField(blank=True, max_length=100)),
                ('p_code', models.CharField(blank=True, max_length=100)),
                ('d_name', models.EmailField(blank=True, max_length=254, unique=True)),
                ('d_number', models.CharField(blank=True, max_length=100)),
                ('dea', models.CharField(blank=True, max_length=100)),
                ('medication', models.CharField(blank=True, max_length=100, null=True)),
                ('dosage', models.CharField(blank=True, max_length=100, null=True)),
                ('frequency', models.CharField(blank=True, max_length=100)),
                ('description', models.CharField(blank=True, max_length=100)),
                ('signature', models.IntegerField(blank=True, null=True)),
                ('dop', models.DateField(blank=True, null=True)),
            ],
        ),
    ]
