# Generated by Django 4.1.5 on 2023-02-26 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prescriptionpatient',
            name='p_code',
        ),
        migrations.AddField(
            model_name='prescriptionpatient',
            name='p_email',
            field=models.EmailField(blank=True, max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='prescriptionpatient',
            name='d_name',
            field=models.CharField(blank=True, max_length=254),
        ),
    ]
