# Generated by Django 4.1.5 on 2023-02-26 22:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0002_remove_prescriptionpatient_p_code_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='prescriptionpatient',
            old_name='p_email',
            new_name='p_code',
        ),
    ]
