# Generated by Django 4.1.5 on 2023-02-26 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0003_rename_p_email_prescriptionpatient_p_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prescriptionpatient',
            name='p_code',
            field=models.EmailField(blank=True, max_length=100),
        ),
    ]
