# Generated by Django 4.1.5 on 2023-02-27 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0004_alter_prescriptionpatient_p_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient', models.CharField(blank=True, max_length=100)),
                ('date', models.DateField(blank=True, max_length=100)),
                ('start_time', models.TimeField(blank=True, max_length=254)),
                ('end_time', models.TimeField(blank=True, max_length=100)),
                ('doctor', models.CharField(blank=True, max_length=100)),
                ('injury', models.CharField(blank=True, max_length=100, null=True)),
                ('note', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
