# Generated by Django 4.1.5 on 2023-02-27 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0005_appointment'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='p_email',
            field=models.EmailField(blank=True, max_length=100),
        ),
    ]
